import type { Metadata } from "next";
import { Poppins, Roboto } from 'next/font/google'
import "./globals.css";
import { ContextProvider } from "@/providers/ContextProvider";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import LoadingComponent from "@/components/LoadingComponent";

const poppins = Poppins({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet" />
      </head>
      <body
        className={`${poppins.className} antialiased`}
      >
        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
        <Toaster position="top-center" toastOptions={{ duration: 2000 }} />
        <ContextProvider>
          <Header />

          {
            children}
        </ContextProvider>
        <Footer />
      </body>
    </html>
  );
}
